# Generated by Django 4.0.6 on 2022-07-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keep_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes_storage',
            name='id',
        ),
        migrations.AddField(
            model_name='notes_storage',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
